// Mock data + localStorage persistence
const STORAGE_KEY = 'creator_crm_data';

// Viggler program contacts (auto-imported, source: 'Viggler')
const VIGGLER_CREATORS = [
  { id: '6b1a920f-ecd5-432d-8b71-4a4b575b9ddc', name: '₊˚꩜ 𝐠𝐫𝐚𝐜𝐞 ✮˚₊', handle: '@.ofol.f', discord_username: 'femboylover_677', primary_platform: 'TikTok', tiktok_url: 'https://www.tiktok.com/@.ofol.f?_r=1&_t=ZP-97U1YKOkAQQ', instagram_url: '', youtube_url: '', twitter_url: '', email: '', whatsapp: '', country: '', timezone: '', niche: 'AI creator', audience_size: 0, average_views: 0, engagement_notes: '', product_fit: 'Viggle', campaign_id: '', creator_type: 'AI creator', source: 'Viggler', owner_id: '__trevor__', current_status: 'Contacted', notes: 'Viggler program contact. Discord: femboylover_677', created_at: '2026-06-29', updated_at: '2026-06-29' },
  { id: '136133a1-c1ce-4802-885f-29c7b428994b', name: '3nck', handle: '@kingvonyappalations', discord_username: '3nck0408', primary_platform: 'TikTok', tiktok_url: 'https://www.tiktok.com/@kingvonyappalations?_r=1&_t=ZT-97QoClkRARq', instagram_url: '', youtube_url: '', twitter_url: '', email: '', whatsapp: '', country: '', timezone: '', niche: 'AI creator', audience_size: 0, average_views: 0, engagement_notes: '', product_fit: 'Viggle', campaign_id: '', creator_type: 'AI creator', source: 'Viggler', owner_id: '__trevor__', current_status: 'Contacted', notes: 'Viggler program contact. Discord: 3nck0408', created_at: '2026-06-29', updated_at: '2026-06-29' },
  { id: '2bd57d84-31f5-40f8-9de6-66ff2e94f9ce', name: 'Alien', handle: '@alienistired', discord_username: 'alienistired', primary_platform: 'TikTok', tiktok_url: 'https://www.tiktok.com/@alienistired', instagram_url: '', youtube_url: 'https://www.youtube.com/@alien_is_tired', twitter_url: '', email: '', whatsapp: '', country: '', timezone: '', niche: 'AI creator', audience_size: 0, average_views: 0, engagement_notes: '', product_fit: 'Viggle', campaign_id: '', creator_type: 'AI creator', source: 'Viggler', owner_id: '__trevor__', current_status: 'Contacted', notes: 'Viggler program contact. Discord: alienistired', created_at: '2026-06-29', updated_at: '2026-06-29' },
  { id: 'c2581470-38ba-4667-a28b-27510400f5b6', name: 'Angry Baldi', handle: '@angrybaldi_', discord_username: 'arthurpintoss', primary_platform: 'TikTok', tiktok_url: 'https://www.tiktok.com/@angrybaldi_?_r=1&_t=ZS-97QkK6CLUcG', instagram_url: '', youtube_url: '', twitter_url: '', email: '', whatsapp: '', country: '', timezone: '', niche: 'AI creator', audience_size: 0, average_views: 0, engagement_notes: '', product_fit: 'Viggle', campaign_id: '', creator_type: 'AI creator', source: 'Viggler', owner_id: '__trevor__', current_status: 'Contacted', notes: 'Viggler program contact. Discord: arthurpintoss', created_at: '2026-06-29', updated_at: '2026-06-29' },
  { id: '408517bd-96c6-4027-8f17-76cc17369ffc', name: 'bopbun', handle: '@bopbun_', discord_username: 'bopbun', primary_platform: 'TikTok', tiktok_url: 'https://www.tiktok.com/@bopbun_?_r=1&_t=ZP-97THTYP85wl', instagram_url: '', youtube_url: '', twitter_url: '', email: '', whatsapp: '', country: '', timezone: '', niche: 'AI creator', audience_size: 0, average_views: 0, engagement_notes: '', product_fit: 'Viggle', campaign_id: '', creator_type: 'AI creator', source: 'Viggler', owner_id: '__trevor__', current_status: 'Contacted', notes: 'Viggler program contact. Discord: bopbun', created_at: '2026-06-29', updated_at: '2026-06-29' },
  { id: 'ef09fa8a-f33e-4498-9169-6152785cb74d', name: 'Brendo123777', handle: '@vigzy_editz', discord_username: 'brendo12377', primary_platform: 'TikTok', tiktok_url: 'https://www.tiktok.com/@vigzy_editz?_r=1&_t=ZN-97Qp2gaD0ti', instagram_url: '', youtube_url: '', twitter_url: '', email: '', whatsapp: '', country: '', timezone: '', niche: 'AI creator', audience_size: 0, average_views: 0, engagement_notes: '', product_fit: 'Viggle', campaign_id: '', creator_type: 'AI creator', source: 'Viggler', owner_id: '__trevor__', current_status: 'Contacted', notes: 'Viggler program contact. Discord: brendo12377', created_at: '2026-06-29', updated_at: '2026-06-29' },
  { id: '0a6cb5b7-d73e-452f-b96c-5d64e8da9b58', name: '𝙱𝚛𝚞𝚌𝚎𝚎', handle: '@yutafan', discord_username: 'yutafan_', primary_platform: 'TikTok', tiktok_url: 'https://www.tiktok.com/@yutafan', instagram_url: '', youtube_url: '', twitter_url: '', email: '', whatsapp: '', country: '', timezone: '', niche: 'AI creator', audience_size: 0, average_views: 0, engagement_notes: '', product_fit: 'Viggle', campaign_id: '', creator_type: 'AI creator', source: 'Viggler', owner_id: '__trevor__', current_status: 'Contacted', notes: 'Viggler program contact. Discord: yutafan_', created_at: '2026-06-29', updated_at: '2026-06-29' },
  { id: 'ef4490d9-93aa-4905-8b03-908aa1e98dec', name: 'Cachimbax', handle: '@cjbaile_oficial', discord_username: 'Cachimbax', primary_platform: 'TikTok', tiktok_url: 'https://www.tiktok.com/@cjbaile_oficial?_r=1&_t=ZS-97QmXEfndGG', instagram_url: 'https://www.instagram.com/cjbaile_oficial?igsh=MThmZnFnMjhzZXk4bw==', youtube_url: '', twitter_url: '', email: '', whatsapp: '', country: '', timezone: '', niche: 'AI creator', audience_size: 0, average_views: 0, engagement_notes: '', product_fit: 'Viggle', campaign_id: '', creator_type: 'AI creator', source: 'Viggler', owner_id: '__trevor__', current_status: 'Contacted', notes: 'Viggler program contact. Discord: Cachimbax', created_at: '2026-06-29', updated_at: '2026-06-29' },
  { id: '368bd042-2ec0-426a-b4dc-8e3749b5a17d', name: 'Gamble ☭', handle: '@collinmtaylorr', discord_username: 'mbappe107_', primary_platform: 'TikTok', tiktok_url: 'https://www.tiktok.com/@collinmtaylorr?_r=1&_t=ZT-97Qmz77LA34', instagram_url: '', youtube_url: '', twitter_url: '', email: '', whatsapp: '', country: '', timezone: '', niche: 'AI creator', audience_size: 0, average_views: 0, engagement_notes: '', product_fit: 'Viggle', campaign_id: '', creator_type: 'AI creator', source: 'Viggler', owner_id: '__trevor__', current_status: 'Contacted', notes: 'Viggler program contact. Discord: mbappe107_', created_at: '2026-06-29', updated_at: '2026-06-29' },
  { id: '60af1bd7-e0be-4ed5-9fee-5aa7566931b6', name: 'GoouMaster', handle: '@jyc.8', discord_username: 'TheDark80', primary_platform: 'TikTok', tiktok_url: 'https://www.tiktok.com/@jyc.8?_r=1&_t=ZP-97SlE9o9hmQ', instagram_url: '', youtube_url: '', twitter_url: '', email: '', whatsapp: '', country: '', timezone: '', niche: 'AI creator', audience_size: 0, average_views: 0, engagement_notes: '', product_fit: 'Viggle', campaign_id: '', creator_type: 'AI creator', source: 'Viggler', owner_id: '__trevor__', current_status: 'Contacted', notes: 'Viggler program contact. Discord: TheDark80', created_at: '2026-06-29', updated_at: '2026-06-29' },
  { id: '28c03de5-668b-4ef0-9227-52a1043b2469', name: 'HaadiPlayzzz on YT', handle: '@haadiplayzzz', discord_username: 'HaadiPlayzzz on YT', primary_platform: 'TikTok', tiktok_url: 'https://www.tiktok.com/@haadiplayzzz', instagram_url: '', youtube_url: 'https://www.youtube.com/@haadiplayzzz', twitter_url: '', email: '', whatsapp: '', country: '', timezone: '', niche: 'AI creator', audience_size: 0, average_views: 0, engagement_notes: '', product_fit: 'Viggle', campaign_id: '', creator_type: 'AI creator', source: 'Viggler', owner_id: '__trevor__', current_status: 'Contacted', notes: 'Viggler program contact. Discord: HaadiPlayzzz on YT', created_at: '2026-06-29', updated_at: '2026-06-29' },
  { id: '9a2c64e7-3285-44c6-a553-e94730ba9761', name: 'HEXADUCK', handle: 'hexaduck', discord_username: 'hexaduck', primary_platform: 'TikTok', tiktok_url: '', instagram_url: '', youtube_url: '', twitter_url: '', email: '', whatsapp: '', country: '', timezone: '', niche: 'AI creator', audience_size: 0, average_views: 0, engagement_notes: '', product_fit: 'Viggle', campaign_id: '', creator_type: 'AI creator', source: 'Viggler', owner_id: '__trevor__', current_status: 'Contacted', notes: 'Viggler program contact. Discord: hexaduck', created_at: '2026-06-29', updated_at: '2026-06-29' },
  { id: '2f47eaa4-16d3-48ee-b13f-2b4184560e24', name: 'Hoseki', handle: '@orbismala', discord_username: '', primary_platform: 'TikTok', tiktok_url: 'https://www.tiktok.com/@orbismala?_r=1&_t=ZN-97Qo83RHdNW', instagram_url: 'https://www.instagram.com/orbismala?igsh=MTB2OGR2ang4MTdoNA==', youtube_url: 'https://youtube.com/@orbismala?si=UlvcsL86cBRFRbkD', twitter_url: '', email: '', whatsapp: '', country: '', timezone: '', niche: 'AI creator', audience_size: 0, average_views: 0, engagement_notes: '', product_fit: 'Viggle', campaign_id: '', creator_type: 'AI creator', source: 'Viggler', owner_id: '__trevor__', current_status: 'Contacted', notes: 'Viggler program contact. Discord:  | Other: https://www.threads.com/@orbismala https://mobile.capcutshare.com/sv2/ZSCJbkACY/ https://www.facebook.com/profile.php?id=100088237879860 https://rumble.com/c/c-3590800', created_at: '2026-06-29', updated_at: '2026-06-29' },
  { id: 'c106ad34-09bb-48c7-a9bf-b56128bd57e0', name: 'Hoshin', handle: '@hoshinproduction', discord_username: 'hoshinanastasia', primary_platform: 'TikTok', tiktok_url: 'https://tiktok.com/@hoshinproduction', instagram_url: '', youtube_url: '', twitter_url: '', email: '', whatsapp: '', country: '', timezone: '', niche: 'AI creator', audience_size: 0, average_views: 0, engagement_notes: '', product_fit: 'Viggle', campaign_id: '', creator_type: 'AI creator', source: 'Viggler', owner_id: '__trevor__', current_status: 'Contacted', notes: 'Viggler program contact. Discord: hoshinanastasia', created_at: '2026-06-29', updated_at: '2026-06-29' },
  { id: '02196d8a-bc3f-417e-91fc-7a6025a5ccec', name: 'jagadarsh', handle: '@bjhs_kirkinator', discord_username: 'jagadarsh', primary_platform: 'TikTok', tiktok_url: 'https://www.tiktok.com/@bjhs_kirkinator', instagram_url: '', youtube_url: '', twitter_url: '', email: '', whatsapp: '', country: '', timezone: '', niche: 'AI creator', audience_size: 0, average_views: 0, engagement_notes: '', product_fit: 'Viggle', campaign_id: '', creator_type: 'AI creator', source: 'Viggler', owner_id: '__trevor__', current_status: 'Contacted', notes: 'Viggler program contact. Discord: jagadarsh', created_at: '2026-06-29', updated_at: '2026-06-29' },
  { id: 'd18483de-0943-42ee-aead-43e4f5e36971', name: 'Jake Dailys', handle: '@jakedailys1', discord_username: 'jakedailys', primary_platform: 'TikTok', tiktok_url: 'https://www.tiktok.com/@jakedailys1', instagram_url: '', youtube_url: 'https://www.youtube.com/@jakedailys', twitter_url: '', email: '', whatsapp: '', country: '', timezone: '', niche: 'AI creator', audience_size: 0, average_views: 0, engagement_notes: '', product_fit: 'Viggle', campaign_id: '', creator_type: 'AI creator', source: 'Viggler', owner_id: '__trevor__', current_status: 'Contacted', notes: 'Viggler program contact. Discord: jakedailys', created_at: '2026-06-29', updated_at: '2026-06-29' },
  { id: 'c2d0e91d-3901-492c-9925-d8323aabf78a', name: 'kxxt', handle: '@real_kxxt', discord_username: '_ttxis (kxxt)', primary_platform: 'TikTok', tiktok_url: 'https://www.tiktok.com/@real_kxxt?_r=1&_t=ZT-97R0Qec2XNd', instagram_url: '', youtube_url: '', twitter_url: '', email: '', whatsapp: '', country: '', timezone: '', niche: 'AI creator', audience_size: 0, average_views: 0, engagement_notes: '', product_fit: 'Viggle', campaign_id: '', creator_type: 'AI creator', source: 'Viggler', owner_id: '__trevor__', current_status: 'Contacted', notes: 'Viggler program contact. Discord: _ttxis (kxxt)', created_at: '2026-06-29', updated_at: '2026-06-29' },
  { id: 'bea6cedf-2641-40a6-8804-b1f784803292', name: 'livid', handle: '@https://tiktok.com/27livid', discord_username: '27livid', primary_platform: 'TikTok', tiktok_url: 'https://tiktok.com/27livid', instagram_url: '', youtube_url: '', twitter_url: '', email: '', whatsapp: '', country: '', timezone: '', niche: 'AI creator', audience_size: 0, average_views: 0, engagement_notes: '', product_fit: 'Viggle', campaign_id: '', creator_type: 'AI creator', source: 'Viggler', owner_id: '__trevor__', current_status: 'Contacted', notes: 'Viggler program contact. Discord: 27livid', created_at: '2026-06-29', updated_at: '2026-06-29' },
  { id: 'b670be3c-5d4b-4dd8-a426-75725eb81972', name: 'matheoalt', handle: '@matstd5', discord_username: 'matheoalt_97391', primary_platform: 'TikTok', tiktok_url: 'matstd5', instagram_url: '', youtube_url: '', twitter_url: '', email: '', whatsapp: '', country: '', timezone: '', niche: 'AI creator', audience_size: 0, average_views: 0, engagement_notes: '', product_fit: 'Viggle', campaign_id: '', creator_type: 'AI creator', source: 'Viggler', owner_id: '__trevor__', current_status: 'Contacted', notes: 'Viggler program contact. Discord: matheoalt_97391', created_at: '2026-06-29', updated_at: '2026-06-29' },
  { id: 'd8e76ddf-f55a-4d9a-9022-533e9fae7f89', name: 'MC-Frezzer', handle: '@story.verses', discord_username: 'mcfrezzer', primary_platform: 'TikTok', tiktok_url: 'https://www.tiktok.com/@story.verses?_r=1&_t=ZG-97QlWuXEdcn', instagram_url: '', youtube_url: '', twitter_url: '', email: '', whatsapp: '', country: '', timezone: '', niche: 'AI creator', audience_size: 0, average_views: 0, engagement_notes: '', product_fit: 'Viggle', campaign_id: '', creator_type: 'AI creator', source: 'Viggler', owner_id: '__trevor__', current_status: 'Contacted', notes: 'Viggler program contact. Discord: mcfrezzer', created_at: '2026-06-29', updated_at: '2026-06-29' },
  { id: '8c79e1e3-1da9-40dd-bad1-0bbec45ecbf5', name: 'Milkies', handle: '@https://www.tiktok.com/t/ZP8scUYCb/', discord_username: 'milkiesssssssssss', primary_platform: 'TikTok', tiktok_url: 'https://www.tiktok.com/t/ZP8scUYCb/', instagram_url: 'https://www.instagram.com/milkiesandechidna?igsh=M2Ezcmc2d3RiZ3Zr&utm_source=qr', youtube_url: 'https://youtube.com/@xoxo87267?si=FQEmFNvWDQii-lIp', twitter_url: '', email: '', whatsapp: '', country: '', timezone: '', niche: 'AI creator', audience_size: 0, average_views: 0, engagement_notes: '', product_fit: 'Viggle', campaign_id: '', creator_type: 'AI creator', source: 'Viggler', owner_id: '__trevor__', current_status: 'Contacted', notes: 'Viggler program contact. Discord: milkiesssssssssss', created_at: '2026-06-29', updated_at: '2026-06-29' },
  { id: 'ce89f278-e5ff-468d-bf1b-6dfe0b211c45', name: 'miningfrog', handle: '@miningfrog2', discord_username: 'miningfrog', primary_platform: 'TikTok', tiktok_url: 'https://www.tiktok.com/@miningfrog2?_r=1&_t=ZT-97RMUnb4eOE', instagram_url: '', youtube_url: '', twitter_url: '', email: '', whatsapp: '', country: '', timezone: '', niche: 'AI creator', audience_size: 0, average_views: 0, engagement_notes: '', product_fit: 'Viggle', campaign_id: '', creator_type: 'AI creator', source: 'Viggler', owner_id: '__trevor__', current_status: 'Contacted', notes: 'Viggler program contact. Discord: miningfrog', created_at: '2026-06-29', updated_at: '2026-06-29' },
  { id: 'd3db263f-891b-4dfe-87c1-66d4777691cb', name: 'Momazos GoldShip', handle: '@momazos.goldship', discord_username: 'momazosgoldship', primary_platform: 'TikTok', tiktok_url: 'https://tiktok.com/@momazos.goldship', instagram_url: 'https://www.instagram.com/momazos.goldship?igsh=MWJzeXN5azVmNmV0cw==', youtube_url: '', twitter_url: '', email: '', whatsapp: '', country: '', timezone: '', niche: 'AI creator', audience_size: 0, average_views: 0, engagement_notes: '', product_fit: 'Viggle', campaign_id: '', creator_type: 'AI creator', source: 'Viggler', owner_id: '__trevor__', current_status: 'Contacted', notes: 'Viggler program contact. Discord: momazosgoldship', created_at: '2026-06-29', updated_at: '2026-06-29' },
  { id: 'c1c1f585-5440-47c0-b407-46afe044c915', name: 'moni', handle: '@dinexhofficial', discord_username: '@dinexhofficial', primary_platform: 'Instagram', tiktok_url: '', instagram_url: 'https://www.instagram.com/dinexh_official?igsh=MXZscHlmNTh5dGVmaw==', youtube_url: '', twitter_url: '', email: '', whatsapp: '', country: '', timezone: '', niche: 'AI creator', audience_size: 0, average_views: 0, engagement_notes: '', product_fit: 'Viggle', campaign_id: '', creator_type: 'AI creator', source: 'Viggler', owner_id: '__trevor__', current_status: 'Contacted', notes: 'Viggler program contact. Discord: @dinexhofficial', created_at: '2026-06-29', updated_at: '2026-06-29' },
  { id: 'a74bba9f-09ad-4f77-b10f-c9355e64f1de', name: 'Pi Pi Pi', handle: '@afidastwygz', discord_username: 'pi_ic', primary_platform: 'TikTok', tiktok_url: 'afidastwygz', instagram_url: '', youtube_url: 'pi_ic', twitter_url: '', email: '', whatsapp: '', country: '', timezone: '', niche: 'AI creator', audience_size: 0, average_views: 0, engagement_notes: '', product_fit: 'Viggle', campaign_id: '', creator_type: 'AI creator', source: 'Viggler', owner_id: '__trevor__', current_status: 'Contacted', notes: 'Viggler program contact. Discord: pi_ic', created_at: '2026-06-29', updated_at: '2026-06-29' },
  { id: '0422c1d3-decc-47c8-afe5-2bb7d4c6d8f8', name: 'pippo', handle: '@pregnanthippo308', discord_username: '.jjd.', primary_platform: 'TikTok', tiktok_url: 'https://www.tiktok.com/@pregnanthippo308?is_from_webapp=1&sender_device=pc', instagram_url: '', youtube_url: '', twitter_url: '', email: '', whatsapp: '', country: '', timezone: '', niche: 'AI creator', audience_size: 0, average_views: 0, engagement_notes: '', product_fit: 'Viggle', campaign_id: '', creator_type: 'AI creator', source: 'Viggler', owner_id: '__trevor__', current_status: 'Contacted', notes: 'Viggler program contact. Discord: .jjd.', created_at: '2026-06-29', updated_at: '2026-06-29' },
  { id: '140c9ee1-5f36-4d2b-8b2f-a7c1e0fb65a7', name: 'Rahand2099', handle: '@rahand2099', discord_username: 'rahand_2099', primary_platform: 'TikTok', tiktok_url: 'https://www.tiktok.com/@rahand2099?_r=1&_t=ZN-97QlE5nNbNu', instagram_url: '', youtube_url: '', twitter_url: '', email: '', whatsapp: '', country: '', timezone: '', niche: 'AI creator', audience_size: 0, average_views: 0, engagement_notes: '', product_fit: 'Viggle', campaign_id: '', creator_type: 'AI creator', source: 'Viggler', owner_id: '__trevor__', current_status: 'Contacted', notes: 'Viggler program contact. Discord: rahand_2099', created_at: '2026-06-29', updated_at: '2026-06-29' },
  { id: '58235df1-d8f5-4bd6-ba9e-ece07128ba5b', name: '𝙍𝘼𝙈𝙀𝙉 𝙎𝙐𝙆𝙐𝙉𝘼 🍜 ⛩', handle: '@first_ramensukuna', discord_username: 'ramensukuna_1', primary_platform: 'TikTok', tiktok_url: 'https://www.tiktok.com/@first_ramensukuna?_r=1&_t=ZN-97QmFjYigha', instagram_url: '', youtube_url: '', twitter_url: '', email: '', whatsapp: '', country: '', timezone: '', niche: 'AI creator', audience_size: 0, average_views: 0, engagement_notes: '', product_fit: 'Viggle', campaign_id: '', creator_type: 'AI creator', source: 'Viggler', owner_id: '__trevor__', current_status: 'Contacted', notes: 'Viggler program contact. Discord: ramensukuna_1', created_at: '2026-06-29', updated_at: '2026-06-29' },
  { id: '12f82c16-0fbf-4408-b06f-ff6624a7b30e', name: 'sejong egg', handle: '@segiongexx', discord_username: 'shut2479', primary_platform: 'TikTok', tiktok_url: 'https://www.tiktok.com/@segiongexx?is_from_webapp=1&sender_device=pc', instagram_url: '', youtube_url: '', twitter_url: '', email: '', whatsapp: '', country: '', timezone: '', niche: 'AI creator', audience_size: 0, average_views: 0, engagement_notes: '', product_fit: 'Viggle', campaign_id: '', creator_type: 'AI creator', source: 'Viggler', owner_id: '__trevor__', current_status: 'Contacted', notes: 'Viggler program contact. Discord: shut2479', created_at: '2026-06-29', updated_at: '2026-06-29' },
  { id: '9ea3c900-226c-4952-b978-7514a03d1871', name: 'SpongebobCovers_Official', handle: '@spongebobcovers_official', discord_username: 'spongebobcovers_official', primary_platform: 'TikTok', tiktok_url: 'spongebobcovers_official', instagram_url: '', youtube_url: 'SPONGEBOBCOVERSARCHIVE', twitter_url: '', email: '', whatsapp: '', country: '', timezone: '', niche: 'AI creator', audience_size: 0, average_views: 0, engagement_notes: '', product_fit: 'Viggle', campaign_id: '', creator_type: 'AI creator', source: 'Viggler', owner_id: '__trevor__', current_status: 'Contacted', notes: 'Viggler program contact. Discord: spongebobcovers_official', created_at: '2026-06-29', updated_at: '2026-06-29' },
  { id: '5e5a6634-9887-4ecd-94f2-0727b3ee8c6c', name: 'sportsballenjoyer007', handle: '@sportsballenjoyer007', discord_username: 'sportsballenjoyer007', primary_platform: 'TikTok', tiktok_url: 'https://www.tiktok.com/@sportsballenjoyer007?_r=1&_t=ZN-97Qs4zH1bPC', instagram_url: '', youtube_url: '', twitter_url: '', email: '', whatsapp: '', country: '', timezone: '', niche: 'AI creator', audience_size: 0, average_views: 0, engagement_notes: '', product_fit: 'Viggle', campaign_id: '', creator_type: 'AI creator', source: 'Viggler', owner_id: '__trevor__', current_status: 'Contacted', notes: 'Viggler program contact. Discord: sportsballenjoyer007', created_at: '2026-06-29', updated_at: '2026-06-29' },
  { id: 'c7749f0f-bf76-422a-9623-b822de0f0614', name: 'Techninja', handle: '@tekninjaaa', discord_username: 'tekninja', primary_platform: 'TikTok', tiktok_url: 'https://www.tiktok.com/@tekninjaaa?_r=1&_t=ZP-97QlSdmKM3C', instagram_url: '', youtube_url: '', twitter_url: '', email: '', whatsapp: '', country: '', timezone: '', niche: 'AI creator', audience_size: 0, average_views: 0, engagement_notes: '', product_fit: 'Viggle', campaign_id: '', creator_type: 'AI creator', source: 'Viggler', owner_id: '__trevor__', current_status: 'Contacted', notes: 'Viggler program contact. Discord: tekninja', created_at: '2026-06-29', updated_at: '2026-06-29' },
  { id: 'e170efb3-75bd-434a-86a4-5890b68aa509', name: 'TheAgenda', handle: '@theagenda', discord_username: 'jamppa7766', primary_platform: 'TikTok', tiktok_url: 'https://www.tiktok.com/@theagenda?_r=1&_t=ZN-97QmB59hCMw', instagram_url: '', youtube_url: '', twitter_url: '', email: '', whatsapp: '', country: '', timezone: '', niche: 'AI creator', audience_size: 0, average_views: 0, engagement_notes: '', product_fit: 'Viggle', campaign_id: '', creator_type: 'AI creator', source: 'Viggler', owner_id: '__trevor__', current_status: 'Contacted', notes: 'Viggler program contact. Discord: jamppa7766', created_at: '2026-06-29', updated_at: '2026-06-29' },
  { id: 'a1382fcd-695e-4f2e-a58b-22aa84900006', name: 'TheOdysseyHadaPurpose', handle: '@theodysseyhad_a_purpose', discord_username: 'contemptuousthing', primary_platform: 'TikTok', tiktok_url: 'https://www.tiktok.com/@theodysseyhad_a_purpose?_r=1&_t=ZT-97Qlngn8Np7', instagram_url: '', youtube_url: '', twitter_url: '', email: '', whatsapp: '', country: '', timezone: '', niche: 'AI creator', audience_size: 0, average_views: 0, engagement_notes: '', product_fit: 'Viggle', campaign_id: '', creator_type: 'AI creator', source: 'Viggler', owner_id: '__trevor__', current_status: 'Contacted', notes: 'Viggler program contact. Discord: contemptuousthing', created_at: '2026-06-29', updated_at: '2026-06-29' },
  { id: '0bbb77b8-b7b4-4de9-a084-f685df28501e', name: 'TronCena', handle: '@ojsglovee', discord_username: 'troncena___', primary_platform: 'TikTok', tiktok_url: 'https://www.tiktok.com/@ojsglovee?_r=1&_t=ZT-97QkYDGnO5V', instagram_url: '', youtube_url: 'https://youtube.com/@ojsglovee?si=89uws6nDORZ72rqC', twitter_url: '', email: '', whatsapp: '', country: '', timezone: '', niche: 'AI creator', audience_size: 0, average_views: 0, engagement_notes: '', product_fit: 'Viggle', campaign_id: '', creator_type: 'AI creator', source: 'Viggler', owner_id: '__trevor__', current_status: 'Contacted', notes: 'Viggler program contact. Discord: troncena___', created_at: '2026-06-29', updated_at: '2026-06-29' },
  { id: '11b0610d-c84e-4027-9373-929b7e47972a', name: 'Valen (@vatrox014)', handle: '@vatrox014', discord_username: 'vatrox014', primary_platform: 'TikTok', tiktok_url: 'https://www.tiktok.com/@vatrox014', instagram_url: 'https://www.instagram.com/vatrox014/', youtube_url: 'https://www.youtube.com/@vatrox014', twitter_url: '', email: '', whatsapp: '', country: '', timezone: '', niche: 'AI creator', audience_size: 0, average_views: 0, engagement_notes: '', product_fit: 'Viggle', campaign_id: '', creator_type: 'AI creator', source: 'Viggler', owner_id: '__trevor__', current_status: 'Contacted', notes: 'Viggler program contact. Discord: vatrox014', created_at: '2026-06-29', updated_at: '2026-06-29' },
  { id: '99d49b50-a216-48cc-9a63-a0314301adee', name: 'Vaseto', handle: '@diobrandobanan', discord_username: '.vaseto', primary_platform: 'TikTok', tiktok_url: 'https://www.tiktok.com/@diobrandobanan?_r=1&_t=ZG-97SMpcXgm6j', instagram_url: '', youtube_url: '', twitter_url: '', email: '', whatsapp: '', country: '', timezone: '', niche: 'AI creator', audience_size: 0, average_views: 0, engagement_notes: '', product_fit: 'Viggle', campaign_id: '', creator_type: 'AI creator', source: 'Viggler', owner_id: '__trevor__', current_status: 'Contacted', notes: 'Viggler program contact. Discord: .vaseto', created_at: '2026-06-29', updated_at: '2026-06-29' },
  { id: '47a4fada-6f38-4ae4-8396-e84d2258de4c', name: 'Vice', handle: '@blazing_memes', discord_username: 'vice8453', primary_platform: 'TikTok', tiktok_url: 'https://www.tiktok.com/@blazing_memes?_r=1&_t=ZT-97QkgA3ZnOY', instagram_url: '', youtube_url: '', twitter_url: '', email: '', whatsapp: '', country: '', timezone: '', niche: 'AI creator', audience_size: 0, average_views: 0, engagement_notes: '', product_fit: 'Viggle', campaign_id: '', creator_type: 'AI creator', source: 'Viggler', owner_id: '__trevor__', current_status: 'Contacted', notes: 'Viggler program contact. Discord: vice8453', created_at: '2026-06-29', updated_at: '2026-06-29' },
  { id: '9255838e-b6ff-4a10-8e02-0743748739ea', name: 'zepphy zepvtra', handle: 'zepphy_monsterz', discord_username: 'zepphy_monsterz', primary_platform: 'Instagram', tiktok_url: '', instagram_url: 'https://instagram.com/mnstr_graphic', youtube_url: '', twitter_url: '', email: '', whatsapp: '', country: '', timezone: '', niche: 'AI creator', audience_size: 0, average_views: 0, engagement_notes: '', product_fit: 'Viggle', campaign_id: '', creator_type: 'AI creator', source: 'Viggler', owner_id: '__trevor__', current_status: 'Contacted', notes: 'Viggler program contact. Discord: zepphy_monsterz | Other: https://threads.com/@mnstr_graphic', created_at: '2026-06-29', updated_at: '2026-06-29' },
  { id: 'b92e7bda-109c-41da-a72b-e75b95464d36', name: '✟REJE✟', handle: '@reje_goat', discord_username: 'yone_the_goat', primary_platform: 'TikTok', tiktok_url: 'https://www.tiktok.com/@reje_goat?_r=1&_t=ZN-97U2nBdk2LO', instagram_url: '', youtube_url: '', twitter_url: '', email: '', whatsapp: '', country: '', timezone: '', niche: 'AI creator', audience_size: 0, average_views: 0, engagement_notes: '', product_fit: 'Viggle', campaign_id: '', creator_type: 'AI creator', source: 'Viggler', owner_id: '__trevor__', current_status: 'Contacted', notes: 'Viggler program contact. Discord: yone_the_goat', created_at: '2026-06-29', updated_at: '2026-06-29' },
  { id: 'dd357dbc-079f-4c87-a744-b3a4777ec535', name: 'Zaha tots live 93 🇬🇶', handle: '@rex.splode34', discord_username: 'zaha_21fcb', primary_platform: 'TikTok', tiktok_url: 'https://www.tiktok.com/@rex.splode34?_r=1&_t=ZS-97WfY8Rzw5l', instagram_url: '', youtube_url: '', twitter_url: '', email: '', whatsapp: '', country: '', timezone: '', niche: 'AI creator', audience_size: 0, average_views: 0, engagement_notes: '', product_fit: 'Viggle', campaign_id: '', creator_type: 'AI creator', source: 'Viggler', owner_id: '__trevor__', current_status: 'Contacted', notes: 'Viggler program contact. Discord: zaha_21fcb', created_at: '2026-06-29', updated_at: '2026-06-29' },
  { id: '2f73d01c-73bf-4a6a-8d6b-9b9d22b6859a', name: 'Bi', handle: '@superhero.editsss,', discord_username: 'bupbe.tinhcam', primary_platform: 'TikTok', tiktok_url: 'https://www.tiktok.com/@superhero.editsss', instagram_url: '', youtube_url: '', twitter_url: '', email: '', whatsapp: '', country: '', timezone: '', niche: 'AI creator', audience_size: 0, average_views: 0, engagement_notes: '', product_fit: 'Viggle', campaign_id: '', creator_type: 'AI creator', source: 'Viggler', owner_id: '__trevor__', current_status: 'Contacted', notes: 'Viggler program contact. Discord: bupbe.tinhcam', created_at: '2026-06-29', updated_at: '2026-06-29' },
  { id: '927eff65-ad5e-44bf-843a-7d7c0e1ce45d', name: 'Word', handle: '@word2mylakers', discord_username: 'wordnl', primary_platform: 'TikTok', tiktok_url: '@word2mylakers', instagram_url: '', youtube_url: '', twitter_url: '', email: '', whatsapp: '', country: '', timezone: '', niche: 'AI creator', audience_size: 0, average_views: 0, engagement_notes: '', product_fit: 'Viggle', campaign_id: '', creator_type: 'AI creator', source: 'Viggler', owner_id: '__trevor__', current_status: 'Contacted', notes: 'Viggler program contact. Discord: wordnl', created_at: '2026-06-29', updated_at: '2026-06-29' },
  { id: 'd7e8f5ea-72c7-4713-8b4e-3356bbb25790', name: 'Faku', handle: '@fakutovt', discord_username: 'Fakuto #6563', primary_platform: 'TikTok', tiktok_url: 'https://www.tiktok.com/@fakutovt', instagram_url: '', youtube_url: 'https://www.youtube.com/@FakutoVT', twitter_url: '', email: '', whatsapp: '', country: '', timezone: '', niche: 'AI creator', audience_size: 0, average_views: 0, engagement_notes: '', product_fit: 'Viggle', campaign_id: '', creator_type: 'AI creator', source: 'Viggler', owner_id: '__trevor__', current_status: 'Contacted', notes: 'Viggler program contact. Discord: Fakuto #6563', created_at: '2026-06-29', updated_at: '2026-06-29' },
  { id: 'cfe4d35c-b40d-4dc2-89fe-e83e68450d54', name: 'Turbofrostynx', handle: '@https://vt.tiktok.com/ZSC2DJMMY/', discord_username: 'this account', primary_platform: 'TikTok', tiktok_url: 'https://vt.tiktok.com/ZSC2DJMMY/', instagram_url: '', youtube_url: '', twitter_url: '', email: '', whatsapp: '', country: '', timezone: '', niche: 'AI creator', audience_size: 0, average_views: 0, engagement_notes: '', product_fit: 'Viggle', campaign_id: '', creator_type: 'AI creator', source: 'Viggler', owner_id: '__trevor__', current_status: 'Contacted', notes: 'Viggler program contact. Discord: this account', created_at: '2026-06-29', updated_at: '2026-06-29' },
  { id: 'b388fd4c-e205-4501-9a6a-79d829e48023', name: 'NIK-T_the0ne4u', handle: '@baldivideos677', discord_username: 'nikt_the0ne4u', primary_platform: 'TikTok', tiktok_url: 'https://www.tiktok.com/@baldivideos677?_r=1&_t=ZP-97UR7H2xUHX', instagram_url: '', youtube_url: '', twitter_url: '', email: '', whatsapp: '', country: '', timezone: '', niche: 'AI creator', audience_size: 0, average_views: 0, engagement_notes: '', product_fit: 'Viggle', campaign_id: '', creator_type: 'AI creator', source: 'Viggler', owner_id: '__trevor__', current_status: 'Contacted', notes: 'Viggler program contact. Discord: nikt_the0ne4u', created_at: '2026-06-29', updated_at: '2026-06-29' },
  { id: '30ea90ae-3346-4a08-9dd0-14d082eca75f', name: 'Maxi', handle: '@waximz', discord_username: 'literallyjoker', primary_platform: 'TikTok', tiktok_url: 'waximz', instagram_url: 'waximz', youtube_url: '', twitter_url: '', email: '', whatsapp: '', country: '', timezone: '', niche: 'AI creator', audience_size: 0, average_views: 0, engagement_notes: '', product_fit: 'Viggle', campaign_id: '', creator_type: 'AI creator', source: 'Viggler', owner_id: '__trevor__', current_status: 'Contacted', notes: 'Viggler program contact. Discord: literallyjoker | Other: X: waximz69', created_at: '2026-06-29', updated_at: '2026-06-29' },
  { id: 'b46102a3-fb7a-4b96-a904-710b7298aef7', name: 'Blyzz', handle: '@blyzzedits', discord_username: 'blyzz / blyzz7', primary_platform: 'TikTok', tiktok_url: 'https://www.tiktok.com/@blyzzedits?_r=1&_t=ZN-97XRzDLPeaM', instagram_url: '', youtube_url: '', twitter_url: '', email: '', whatsapp: '', country: '', timezone: '', niche: 'AI creator', audience_size: 0, average_views: 0, engagement_notes: '', product_fit: 'Viggle', campaign_id: '', creator_type: 'AI creator', source: 'Viggler', owner_id: '__trevor__', current_status: 'Contacted', notes: 'Viggler program contact. Discord: blyzz / blyzz7', created_at: '2026-06-29', updated_at: '2026-06-29' },
  { id: '05b08264-01c2-4367-a315-837ed32febab', name: 'clax', handle: '@theyluv.loukas', discord_username: 'loukas.0', primary_platform: 'TikTok', tiktok_url: 'https://www.tiktok.com/@theyluv.loukas?_r=1&_t=ZT-97b98rzeJgc', instagram_url: '', youtube_url: '', twitter_url: '', email: '', whatsapp: '', country: '', timezone: '', niche: 'AI creator', audience_size: 0, average_views: 0, engagement_notes: '', product_fit: 'Viggle', campaign_id: '', creator_type: 'AI creator', source: 'Viggler', owner_id: '__trevor__', current_status: 'Contacted', notes: 'Viggler program contact. Discord: loukas.0', created_at: '2026-06-29', updated_at: '2026-06-29' },
  { id: '7f0290b5-a031-465b-8625-6ec1c64c6714', name: 'BlackHercules', handle: '@pkhers,', discord_username: '1blackhercules', primary_platform: 'TikTok', tiktok_url: '@pkhers,', instagram_url: '', youtube_url: '1blackhercules', twitter_url: '', email: '', whatsapp: '', country: '', timezone: '', niche: 'AI creator', audience_size: 0, average_views: 0, engagement_notes: '', product_fit: 'Viggle', campaign_id: '', creator_type: 'AI creator', source: 'Viggler', owner_id: '__trevor__', current_status: 'Contacted', notes: 'Viggler program contact. Discord: 1blackhercules | Other: Viggle: BlackHercules', created_at: '2026-06-29', updated_at: '2026-06-29' },
  { id: 'b80b3a84-1026-4dc0-a049-cf0326dd1a5c', name: 'Z1TH0S', handle: '@z1th0s', discord_username: 'z1th0s', primary_platform: 'TikTok', tiktok_url: 'https://www.tiktok.com/@z1th0s?_r=1&_t=ZN-97aZ0A9KhTq', instagram_url: 'https://www.instagram.com/z1th0s?igsh=bXprdGVvNXZ4anBv&utm_source=qr', youtube_url: 'https://youtube.com/@z1th0s?si=Jz9aPX84snqxOBjm', twitter_url: '', email: '', whatsapp: '', country: '', timezone: '', niche: 'AI creator', audience_size: 0, average_views: 0, engagement_notes: '', product_fit: 'Viggle', campaign_id: '', creator_type: 'AI creator', source: 'Viggler', owner_id: '__trevor__', current_status: 'Contacted', notes: 'Viggler program contact. Discord: z1th0s', created_at: '2026-06-29', updated_at: '2026-06-29' },
  { id: '7c870cff-4686-402e-91c2-ca3937479431', name: 'nokk', handle: '@trulynokk', discord_username: 'trulynokk', primary_platform: 'TikTok', tiktok_url: 'https://www.tiktok.com/@trulynokk', instagram_url: '', youtube_url: '', twitter_url: '', email: '', whatsapp: '', country: '', timezone: '', niche: 'AI creator', audience_size: 0, average_views: 0, engagement_notes: '', product_fit: 'Viggle', campaign_id: '', creator_type: 'AI creator', source: 'Viggler', owner_id: '__trevor__', current_status: 'Contacted', notes: 'Viggler program contact. Discord: trulynokk', created_at: '2026-06-29', updated_at: '2026-06-29' },
  { id: 'a866c89e-dfbb-4b80-9756-401e0c841561', name: 'Pray', handle: '@praayyyy', discord_username: 'praaayy.', primary_platform: 'TikTok', tiktok_url: 'https://www.tiktok.com/@praayyyy?_r=1&_t=ZT-97Qq6F8Qymk', instagram_url: '', youtube_url: '', twitter_url: '', email: '', whatsapp: '', country: '', timezone: '', niche: 'AI creator', audience_size: 0, average_views: 0, engagement_notes: '', product_fit: 'Viggle', campaign_id: '', creator_type: 'AI creator', source: 'Viggler', owner_id: '__trevor__', current_status: 'Contacted', notes: 'Viggler program contact. Discord: praaayy.', created_at: '2026-06-29', updated_at: '2026-06-29' },
  { id: '6bde07aa-506c-4a3f-9faf-0d20a33bcca9', name: 'Eren Yeager 🖤', handle: 'ere_mikasa', discord_username: 'ere_mikasa', primary_platform: 'Instagram', tiktok_url: '', instagram_url: 'https://www.instagram.com/eremikasa7?igsh=MTR3aDdva3dnZTI1YQ==', youtube_url: '', twitter_url: '', email: '', whatsapp: '', country: '', timezone: '', niche: 'AI creator', audience_size: 0, average_views: 0, engagement_notes: '', product_fit: 'Viggle', campaign_id: '', creator_type: 'AI creator', source: 'Viggler', owner_id: '__trevor__', current_status: 'Contacted', notes: 'Viggler program contact. Discord: ere_mikasa', created_at: '2026-06-29', updated_at: '2026-06-29' },
  { id: '0ae52dd2-7bcf-40d5-be28-366e3ff33f5b', name: 'Capcrab', handle: '@capcrabcove', discord_username: 'capcrab', primary_platform: 'TikTok', tiktok_url: 'https://www.tiktok.com/@capcrabcove?_r=1&_t=ZT-97TlHFAhckf', instagram_url: '', youtube_url: 'https://youtube.com/@capcrab?si=kRug0qdPOkKvTx6Y', twitter_url: '', email: '', whatsapp: '', country: '', timezone: '', niche: 'AI creator', audience_size: 0, average_views: 0, engagement_notes: '', product_fit: 'Viggle', campaign_id: '', creator_type: 'AI creator', source: 'Viggler', owner_id: '__trevor__', current_status: 'Contacted', notes: 'Viggler program contact. Discord: capcrab', created_at: '2026-06-29', updated_at: '2026-06-29' },
];

const defaultData = {
  creators: [
    { id: '1', name: 'Jerron Jacques', handle: '@jerron_jacques', primary_platform: 'TikTok', tiktok_url: 'https://tiktok.com/@jerron_jacques', instagram_url: 'https://instagram.com/jerron_jacques', youtube_url: '', twitter_url: '', discord_username: '', email: '', whatsapp: '', country: '', timezone: '', niche: 'Short-form video', audience_size: 33100, average_views: 0, engagement_notes: '33.1K TikTok followers (Jun 2026)', product_fit: 'PINOC', creator_type: 'TikTok creator', source: 'Existing partner', owner_id: '1', current_status: 'Content in progress', notes: 'Needs weekly content calendar and 3 links per week. 12 videos/month at $250/video. Approval needed: preview, caption, posting date, tags.', created_at: '2026-06-01', updated_at: '2026-06-26' },
    { id: '2', name: 'Brock Mair', handle: '@brockcreativeofficial', primary_platform: 'Instagram', tiktok_url: 'https://tiktok.com/@brockcreative', instagram_url: 'https://instagram.com/brockcreativeofficial', youtube_url: '', twitter_url: '', discord_username: '', email: '', whatsapp: '', country: '', timezone: '', niche: 'Short-form video', audience_size: 174000, average_views: 0, engagement_notes: '174K Instagram followers (Jun 2026)', product_fit: 'PINOC', creator_type: 'Instagram creator', source: 'Existing partner', owner_id: '1', current_status: 'Contract sent', notes: 'We need to make video assets for them. Contract sent, waiting on draft/schedule. Approval needed: preview, caption, posting date, tags.', created_at: '2026-06-10', updated_at: '2026-06-26' },
    { id: '3', name: 'Tom (SoloDev)', handle: '@SoloDevTom', primary_platform: 'YouTube', tiktok_url: '', instagram_url: '', youtube_url: 'https://youtube.com/@SoloDevTom', twitter_url: '', discord_username: '', email: '', whatsapp: '', country: '', timezone: '', niche: 'Unity / game dev workflow', audience_size: 0, average_views: 0, engagement_notes: 'Subscriber count not confirmed — check youtube.com/@SoloDevTom directly', product_fit: 'PINOC', creator_type: 'YouTube creator', source: 'Existing partner', owner_id: '1', current_status: 'Contract sent', notes: 'Ghosting me. Follow up on signed agreement. $600 upfront deal for 1 dedicated YouTube video.', created_at: '2026-06-01', updated_at: '2026-06-26' },
    { id: '4', name: 'Patrikas', handle: '@bypatrikas', primary_platform: 'Instagram', tiktok_url: '', instagram_url: 'https://instagram.com/bypatrikas', youtube_url: '', twitter_url: '', discord_username: '', email: '', whatsapp: '', country: '', timezone: '', niche: '3D animator / mocap', audience_size: 31000, average_views: 0, engagement_notes: '31K Instagram followers (Jun 2026). Clients: Adidas, Hot Wheels, Wrangler, FaZe Clan, StockX', product_fit: 'PINOC', creator_type: '3D animator', source: 'Existing partner', owner_id: '1', current_status: 'Content in progress', notes: 'Working on mocap part now. WIP render sent. Make sure mocap/character animation is the main focus. Due June 28-29.', created_at: '2026-06-15', updated_at: '2026-06-26' },
    { id: '5', name: 'Daniele Vieira', handle: '@alitiledani', primary_platform: 'TikTok', tiktok_url: '', instagram_url: 'https://instagram.com/alitiledani', youtube_url: '', twitter_url: '', discord_username: '', email: '', whatsapp: '', country: '', timezone: '', niche: 'Visual / video art', audience_size: 0, average_views: 0, engagement_notes: 'Follower count not found online — check instagram.com/alitiledani directly', product_fit: 'PINOC', creator_type: 'TikTok creator', source: 'Existing partner', owner_id: '1', current_status: 'Content in progress', notes: 'Payment $400 sent. She confirmed payment, everything on track. Base $800. Bonus: +$200 if 100k views, +$200 if 200k views. Due June 30.', created_at: '2026-06-20', updated_at: '2026-06-26' },
    { id: '6', name: 'Samarth Kapoor', handle: '@samarthsart', primary_platform: 'Instagram', tiktok_url: '', instagram_url: 'https://instagram.com/samarthsart', youtube_url: '', twitter_url: '', discord_username: '', email: '', whatsapp: '', country: '', timezone: '', niche: 'Digital art / workflow', audience_size: 5692, average_views: 0, engagement_notes: '5.7K Instagram followers (Jun 2026)', product_fit: 'PINOC', creator_type: 'Instagram creator', source: 'Existing partner', owner_id: '1', current_status: 'Content in progress', notes: 'Paid $200 in full. Concept got bigger, wants to present it better. Due July 12 (was July 5). Ask for progress update next week. Workflow + result video.', created_at: '2026-06-20', updated_at: '2026-06-26' },
  ],
  campaigns: [
    { id: '1', campaign_name: 'PINOC Creator Launch', product: 'PINOC', campaign_type: 'Paid partnership', start_date: '2026-06-01', end_date: '2026-08-31', campaign_status: 'Active', landing_page_url: '', cta_link: '', utm_link: '', notes: 'Main PINOC creator campaign — workflow + result videos', created_at: '2026-06-01', updated_at: '2026-06-01' },
  ],
  deals: [
    { id: '1', creator_id: '1', campaign_id: '1', deal_name: 'Jerron Jacques — 12 PINOC videos/month', product: 'PINOC', platform: 'TikTok', deliverable_type: 'TikTok video', number_of_deliverables: 12, rate: 250, currency: 'USD', payment_terms: 'Weekly PayPal after approved + posted', usage_rights: 'Yes', repost_permission: 'Yes', whitelisting_permission: 'No', contract_required: true, contract_status: 'Signed', internal_approver: 'Jeremy', owner_id: '1', deal_status: 'In progress', start_date: '2026-06-01', due_date: '2026-06-28', posting_date: '', notes: '3 videos/week cadence. Needs weekly content calendar and 3 links per week. Approval: preview, caption, posting date, tags.', created_at: '2026-06-01', updated_at: '2026-06-26' },
    { id: '2', creator_id: '2', campaign_id: '1', deal_name: 'Brock Mair — 1 PINOC video', product: 'PINOC', platform: 'Instagram', deliverable_type: 'Instagram Reel', number_of_deliverables: 1, rate: 1000, currency: 'USD', payment_terms: 'Flat fee, bank transfer', usage_rights: 'Yes', repost_permission: 'Yes', whitelisting_permission: 'No', contract_required: true, contract_status: 'Sent', internal_approver: 'Jeremy', owner_id: '1', deal_status: 'Contract sent', start_date: '2026-06-20', due_date: '', posting_date: '', notes: 'We need to make video assets for them. Waiting on draft/schedule. Approval: preview, caption, posting date, tags.', created_at: '2026-06-20', updated_at: '2026-06-26' },
    { id: '3', creator_id: '3', campaign_id: '1', deal_name: 'Tom SoloDev — 1 YouTube video', product: 'PINOC', platform: 'YouTube', deliverable_type: 'YouTube video', number_of_deliverables: 1, rate: 600, currency: 'USD', payment_terms: 'Upfront', usage_rights: 'Yes', repost_permission: 'Yes', whitelisting_permission: 'No', contract_required: true, contract_status: 'Sent', internal_approver: 'Jeremy', owner_id: '1', deal_status: 'Contract sent', start_date: '2026-06-01', due_date: '', posting_date: '', notes: 'Ghosting. Follow up on signed agreement. Unity/game dev workflow focus.', created_at: '2026-06-01', updated_at: '2026-06-26' },
    { id: '4', creator_id: '4', campaign_id: '1', deal_name: 'Patrikas — Animation + PINOC integration', product: 'PINOC', platform: 'Instagram', deliverable_type: 'Instagram Reel', number_of_deliverables: 1, rate: 1000, currency: 'USD', payment_terms: 'Flat fee', usage_rights: 'Yes', repost_permission: 'Yes', whitelisting_permission: 'No', contract_required: true, contract_status: 'Signed', internal_approver: 'Jeremy', owner_id: '1', deal_status: 'In progress', start_date: '2026-06-15', due_date: '2026-06-29', posting_date: '', notes: 'WIP render sent. Mocap/character animation must be main focus. Working on mocap part now.', created_at: '2026-06-15', updated_at: '2026-06-26' },
    { id: '5', creator_id: '5', campaign_id: '1', deal_name: 'Daniele Vieira — Visual/video', product: 'PINOC', platform: 'TikTok', deliverable_type: 'TikTok video', number_of_deliverables: 1, rate: 800, currency: 'USD', payment_terms: '$400 upfront, $400 on delivery. Bonus: +$200 at 100k views, +$200 at 200k views', usage_rights: 'Yes', repost_permission: 'Yes', whitelisting_permission: 'No', contract_required: true, contract_status: 'Signed', internal_approver: 'Jeremy', owner_id: '1', deal_status: 'In progress', start_date: '2026-06-20', due_date: '2026-06-30', posting_date: '', notes: '$400 already sent. She confirmed payment and said everything is on track.', created_at: '2026-06-20', updated_at: '2026-06-26' },
    { id: '6', creator_id: '6', campaign_id: '1', deal_name: 'Samarth Kapoor — Workflow + result video', product: 'PINOC', platform: 'Instagram', deliverable_type: 'Instagram Reel', number_of_deliverables: 1, rate: 200, currency: 'USD', payment_terms: 'Paid in full upfront', usage_rights: 'Yes', repost_permission: 'Yes', whitelisting_permission: 'No', contract_required: true, contract_status: 'Signed', internal_approver: 'Jeremy', owner_id: '1', deal_status: 'In progress', start_date: '2026-06-20', due_date: '2026-07-12', posting_date: '', notes: 'Concept got bigger, wants to present it better. Due July 12 (was July 5). Ask for progress update next week.', created_at: '2026-06-20', updated_at: '2026-06-26' },
  ],
  outreach: [
    { id: '1', creator_id: '1', owner_id: '1', outreach_channel: 'DM', outreach_status: 'Contract signed', date_contacted: '2026-06-01', last_response_date: '2026-06-26', next_follow_up_date: '2026-06-28', message_summary: 'Signed. 12 PINOC videos/month at $250/video. 3/week cadence. Needs weekly content calendar and 3 links per week.', notes: 'Approval required: preview, caption, posting date, tags before each post.', created_at: '2026-06-01', updated_at: '2026-06-26' },
    { id: '2', creator_id: '2', owner_id: '1', outreach_channel: 'DM', outreach_status: 'Contract sent', date_contacted: '2026-06-20', last_response_date: '2026-06-26', next_follow_up_date: '2026-06-29', message_summary: 'Contract sent. $1,000 flat for 1 PINOC video. Waiting on draft/schedule.', notes: 'We need to build video assets for them first.', created_at: '2026-06-20', updated_at: '2026-06-26' },
    { id: '3', creator_id: '3', owner_id: '1', outreach_channel: 'DM', outreach_status: 'Contract sent', date_contacted: '2026-06-01', last_response_date: '2026-06-15', next_follow_up_date: '2026-06-27', message_summary: '$600 upfront deal for 1 dedicated YouTube video. Need to follow up on signed agreement.', notes: 'Not responding. Ghosting.', created_at: '2026-06-01', updated_at: '2026-06-26' },
    { id: '4', creator_id: '4', owner_id: '1', outreach_channel: 'DM', outreach_status: 'Content in progress', date_contacted: '2026-06-15', last_response_date: '2026-06-26', next_follow_up_date: '2026-06-29', message_summary: '$1,000 deal. WIP render sent. Working on mocap part now. Due June 28-29.', notes: 'Make sure mocap/character animation is the main focus.', created_at: '2026-06-15', updated_at: '2026-06-26' },
    { id: '5', creator_id: '5', owner_id: '1', outreach_channel: 'DM', outreach_status: 'Content in progress', date_contacted: '2026-06-20', last_response_date: '2026-06-26', next_follow_up_date: '2026-07-01', message_summary: '$400 sent. She confirmed payment. Everything on track. Due June 30.', notes: 'Bonus: +$200 at 100k views, +$200 at 200k views.', created_at: '2026-06-20', updated_at: '2026-06-26' },
    { id: '6', creator_id: '6', owner_id: '1', outreach_channel: 'DM', outreach_status: 'Content in progress', date_contacted: '2026-06-20', last_response_date: '2026-06-26', next_follow_up_date: '2026-07-05', message_summary: 'Paid $200 in full. Concept got bigger, delayed to July 12.', notes: 'Ask for progress update next week.', created_at: '2026-06-20', updated_at: '2026-06-26' },
  ],
  contracts: [
    { id: '1', creator_id: '1', deal_id: '1', campaign_id: '1', contract_name: 'Jerron Jacques — PINOC Monthly', contract_type: 'TikTok creator agreement', template_file_url: '', signed_contract_file_url: '', date_sent: '2026-06-01', date_signed: '2026-06-01', contract_status: 'Signed', usage_rights_included: true, repost_rights_included: true, payment_terms_included: true, notes: '$250/video, weekly PayPal after approved + posted.', created_at: '2026-06-01', updated_at: '2026-06-01' },
    { id: '2', creator_id: '2', deal_id: '2', campaign_id: '1', contract_name: 'Brock Mair — PINOC One-time', contract_type: 'Instagram Reel agreement', template_file_url: '', signed_contract_file_url: '', date_sent: '2026-06-20', date_signed: '', contract_status: 'Sent', usage_rights_included: true, repost_rights_included: true, payment_terms_included: true, notes: '$1,000 flat, bank transfer.', created_at: '2026-06-20', updated_at: '2026-06-26' },
    { id: '3', creator_id: '3', deal_id: '3', campaign_id: '1', contract_name: 'Tom SoloDev — YouTube PINOC', contract_type: 'YouTube sponsorship agreement', template_file_url: '', signed_contract_file_url: '', date_sent: '2026-06-01', date_signed: '', contract_status: 'Sent', usage_rights_included: true, repost_rights_included: true, payment_terms_included: true, notes: '$600 upfront. Not responding.', created_at: '2026-06-01', updated_at: '2026-06-26' },
    { id: '4', creator_id: '4', deal_id: '4', campaign_id: '1', contract_name: 'Patrikas — PINOC Animation', contract_type: 'PINOC workflow video agreement', template_file_url: '', signed_contract_file_url: '', date_sent: '2026-06-15', date_signed: '2026-06-15', contract_status: 'Signed', usage_rights_included: true, repost_rights_included: true, payment_terms_included: true, notes: '$1,000 flat.', created_at: '2026-06-15', updated_at: '2026-06-15' },
    { id: '5', creator_id: '5', deal_id: '5', campaign_id: '1', contract_name: 'Daniele Vieira — PINOC Visual', contract_type: 'TikTok creator agreement', template_file_url: '', signed_contract_file_url: '', date_sent: '2026-06-20', date_signed: '2026-06-20', contract_status: 'Signed', usage_rights_included: true, repost_rights_included: true, payment_terms_included: true, notes: '$800 base + view bonuses.', created_at: '2026-06-20', updated_at: '2026-06-20' },
    { id: '6', creator_id: '6', deal_id: '6', campaign_id: '1', contract_name: 'Samarth Kapoor — PINOC Workflow', contract_type: 'PINOC workflow video agreement', template_file_url: '', signed_contract_file_url: '', date_sent: '2026-06-20', date_signed: '2026-06-20', contract_status: 'Signed', usage_rights_included: true, repost_rights_included: true, payment_terms_included: true, notes: '$200 paid in full.', created_at: '2026-06-20', updated_at: '2026-06-20' },
  ],
  videos: [
    { id: '1', creator_id: '1', deal_id: '1', campaign_id: '1', project: 'PINOC', video_title: 'Jerron PINOC Video — Week 1 #1', platform: 'TikTok', deliverable_type: 'TikTok video', contract_signed_date: '2026-06-01', draft_due_date: '2026-06-27', draft_submitted_date: null, review_due_date: '2026-06-28', scheduled_post_date: '2026-06-28', actual_post_date: null, video_status: 'Awaiting Draft', approval_status: 'Not submitted', repost_allowed: true, post_url: '', file_url: '', payment_status: 'Not started', owner_id: '1', notes: 'Needs: preview, caption, posting date, tags before approval', created_at: '2026-06-26', updated_at: '2026-06-26' },
    { id: '2', creator_id: '1', deal_id: '1', campaign_id: '1', project: 'PINOC', video_title: 'Jerron PINOC Video — Week 1 #2', platform: 'TikTok', deliverable_type: 'TikTok video', contract_signed_date: '2026-06-01', draft_due_date: '2026-06-29', draft_submitted_date: null, review_due_date: '2026-06-30', scheduled_post_date: '2026-06-30', actual_post_date: null, video_status: 'Awaiting Draft', approval_status: 'Not submitted', repost_allowed: true, post_url: '', file_url: '', payment_status: 'Not started', owner_id: '1', notes: '', created_at: '2026-06-26', updated_at: '2026-06-26' },
    { id: '3', creator_id: '4', deal_id: '4', campaign_id: '1', project: 'PINOC', video_title: 'Patrikas — Mocap + PINOC Workflow', platform: 'Instagram', deliverable_type: 'Instagram Reel', contract_signed_date: '2026-06-15', draft_due_date: '2026-06-28', draft_submitted_date: null, review_due_date: '2026-06-29', scheduled_post_date: '2026-06-29', actual_post_date: null, video_status: 'In Review', approval_status: 'Pending review', repost_allowed: true, post_url: '', file_url: '', payment_status: 'Not started', owner_id: '1', notes: 'WIP render sent. Mocap/character animation must be main focus.', created_at: '2026-06-15', updated_at: '2026-06-26' },
    { id: '4', creator_id: '5', deal_id: '5', campaign_id: '1', project: 'PINOC', video_title: 'Daniele Vieira — PINOC Visual', platform: 'TikTok', deliverable_type: 'TikTok video', contract_signed_date: '2026-06-20', draft_due_date: '2026-06-29', draft_submitted_date: null, review_due_date: '2026-06-30', scheduled_post_date: '2026-06-30', actual_post_date: null, video_status: 'Awaiting Draft', approval_status: 'Not submitted', repost_allowed: true, post_url: '', file_url: '', payment_status: 'Not started', owner_id: '1', notes: 'Payment sent. She confirmed everything on track.', created_at: '2026-06-20', updated_at: '2026-06-26' },
    { id: '5', creator_id: '6', deal_id: '6', campaign_id: '1', project: 'PINOC', video_title: 'Samarth Kapoor — Workflow + Result', platform: 'Instagram', deliverable_type: 'Instagram Reel', contract_signed_date: '2026-06-20', draft_due_date: '2026-07-12', draft_submitted_date: null, review_due_date: '2026-07-13', scheduled_post_date: '2026-07-14', actual_post_date: null, video_status: 'Awaiting Draft', approval_status: 'Not submitted', repost_allowed: true, post_url: '', file_url: '', payment_status: 'Paid', owner_id: '1', notes: 'Concept got bigger, delayed from July 5. Ask for update next week.', created_at: '2026-06-20', updated_at: '2026-06-26' },
  ],
  payments: [
    { id: '1', creator_id: '1', deal_id: '1', campaign_id: '1', amount: 250, currency: 'USD', payment_method: 'PayPal', payment_info_received: true, invoice_required: false, invoice_received: false, invoice_file_url: '', payment_approved: false, payment_sent: false, payment_date: null, payment_status: 'Not started', payment_owner_id: '1', notes: '$250 per video, paid weekly via PayPal after approved + posted.', created_at: '2026-06-26', updated_at: '2026-06-26' },
    { id: '2', creator_id: '2', deal_id: '2', campaign_id: '1', amount: 1000, currency: 'USD', payment_method: 'Bank transfer', payment_info_received: false, invoice_required: false, invoice_received: false, invoice_file_url: '', payment_approved: false, payment_sent: false, payment_date: null, payment_status: 'Payment info needed', payment_owner_id: '1', notes: '$1,000 flat fee via bank transfer.', created_at: '2026-06-26', updated_at: '2026-06-26' },
    { id: '3', creator_id: '3', deal_id: '3', campaign_id: '1', amount: 600, currency: 'USD', payment_method: 'Other', payment_info_received: false, invoice_required: false, invoice_received: false, invoice_file_url: '', payment_approved: false, payment_sent: false, payment_date: null, payment_status: 'Not started', payment_owner_id: '1', notes: '$600 upfront. Waiting for reply / signed agreement first.', created_at: '2026-06-26', updated_at: '2026-06-26' },
    { id: '4', creator_id: '4', deal_id: '4', campaign_id: '1', amount: 1000, currency: 'USD', payment_method: 'Other', payment_info_received: false, invoice_required: false, invoice_received: false, invoice_file_url: '', payment_approved: false, payment_sent: false, payment_date: null, payment_status: 'Not started', payment_owner_id: '1', notes: '$1,000 flat. Pay after delivery.', created_at: '2026-06-26', updated_at: '2026-06-26' },
    { id: '5', creator_id: '5', deal_id: '5', campaign_id: '1', amount: 400, currency: 'USD', payment_method: 'PayPal', payment_info_received: true, invoice_required: false, invoice_received: false, invoice_file_url: '', payment_approved: true, payment_sent: true, payment_date: '2026-06-20', payment_status: 'Paid', payment_owner_id: '1', notes: '$400 first instalment sent. $400 remaining on delivery. Bonus: +$200 at 100k views, +$200 at 200k views.', created_at: '2026-06-20', updated_at: '2026-06-26' },
    { id: '6', creator_id: '6', deal_id: '6', campaign_id: '1', amount: 200, currency: 'USD', payment_method: 'PayPal', payment_info_received: true, invoice_required: false, invoice_received: false, invoice_file_url: '', payment_approved: true, payment_sent: true, payment_date: '2026-06-20', payment_status: 'Paid', payment_owner_id: '1', notes: '$200 paid in full upfront.', created_at: '2026-06-20', updated_at: '2026-06-26' },
  ],
  content_assets: [],
  templates: [
    { id: '1', template_name: 'Initial TikTok Outreach', template_type: 'Outreach', product: 'Viggle', file_url: '', template_text: "Hey [Name]! 👋 Love your content — your [recent video] was 🔥. I'm from Viggle AI (the AI video generator). We'd love to partner with you on a paid collab for our [Campaign Name] campaign. Interested in hearing more? Happy to send over details!", notes: '', created_at: '2026-06-01', updated_at: '2026-06-01' },
    { id: '2', template_name: 'Follow-Up (No Response)', template_type: 'Outreach', product: 'Both', file_url: '', template_text: "Hey [Name]! Just following up on my last message about a paid collab with [Viggle/PINOC]. We think you'd be a great fit — let me know if you're open to chatting! 🙌", notes: '', created_at: '2026-06-01', updated_at: '2026-06-01' },
    { id: '3', template_name: 'Rate Negotiation', template_type: 'Outreach', product: 'Both', file_url: '', template_text: "Thanks for getting back to us! We really love your content and want to make this work. Our budget for this partnership is $[AMOUNT] for [NUMBER] videos. We also include full usage rights + repost permission. Does that work for you?", notes: '', created_at: '2026-06-01', updated_at: '2026-06-01' },
    { id: '4', template_name: 'Content Reminder', template_type: 'Outreach', product: 'Both', file_url: '', template_text: "Hey [Name]! Just a friendly reminder that the draft for [Video Title] is due [DATE]. Let us know if you need anything from our side — brief, assets, etc. Can't wait to see it! 🎬", notes: '', created_at: '2026-06-01', updated_at: '2026-06-01' },
    { id: '5', template_name: 'Repost Permission Ask', template_type: 'Outreach', product: 'Both', file_url: '', template_text: "Hey [Name]! Your video has been performing amazing 🔥 We'd love to repost it on our [Viggle/PINOC] account. We'll tag you, of course. Is that okay?", notes: '', created_at: '2026-06-01', updated_at: '2026-06-01' },
    { id: '6', template_name: 'Viggle TikTok Brief', template_type: 'Brief', product: 'Viggle', file_url: '', template_text: "CAMPAIGN BRIEF — VIGGLE AI\n\nBrand: Viggle AI\nCampaign: [Campaign Name]\nPlatform: TikTok\n\nObjective: Drive downloads and awareness of Viggle AI's video generation tool.\n\nKey Message: Viggle AI lets you put anyone in any video. Create incredible AI videos in seconds.\n\nDeliverables:\n- [X] TikTok videos\n- Min [X] seconds\n- Must include: @viggle tag, [Link in bio CTA]\n\nDo's:\n- Show the tool in action\n- Use trending audio\n- Be authentic\n\nDon'ts:\n- Do not make medical/health claims\n- Do not use competitor branding\n\nDeadlines:\n- Draft due: [DATE]\n- Review by: [DATE]\n- Post date: [DATE]", notes: '', created_at: '2026-06-01', updated_at: '2026-06-01' },
  ],
  campaign_links: [
    { id: '1', campaign_id: '1', campaign_name: 'Viggle FIFA Summer 2026', product: 'Viggle', landing_page_url: 'https://viggle.ai/fifa', cta_link: 'https://viggle.ai/download', utm_link: 'https://viggle.ai/?utm_source=tiktok&utm_campaign=fifa2026', creator_specific_link: 'https://viggle.ai/?ref=[CREATOR]', tracking_link: '', notes: 'Replace [CREATOR] with creator handle', created_at: '2026-06-01', updated_at: '2026-06-01' },
  ],
  activity_log: [
    { id: '1', user_id: '1', action: 'Creator added', related_creator_id: '1', related_deal_id: null, related_campaign_id: null, related_payment_id: null, related_video_id: null, old_value: null, new_value: 'Jerron Jacques', timestamp: '2026-06-01T10:00:00Z' },
    { id: '2', user_id: '1', action: 'Contract signed', related_creator_id: '1', related_deal_id: '1', related_campaign_id: null, related_payment_id: null, related_video_id: null, old_value: null, new_value: 'Signed', timestamp: '2026-06-01T11:00:00Z' },
    { id: '3', user_id: '1', action: 'Payment sent', related_creator_id: '5', related_deal_id: '5', related_campaign_id: null, related_payment_id: '5', related_video_id: null, old_value: 'Not started', new_value: 'Paid', timestamp: '2026-06-20T14:00:00Z' },
    { id: '4', user_id: '1', action: 'Payment sent', related_creator_id: '6', related_deal_id: '6', related_campaign_id: null, related_payment_id: '6', related_video_id: null, old_value: 'Not started', new_value: 'Paid', timestamp: '2026-06-20T14:30:00Z' },
    { id: '5', user_id: '1', action: 'Contract sent', related_creator_id: '3', related_deal_id: '3', related_campaign_id: null, related_payment_id: null, related_video_id: null, old_value: null, new_value: 'Sent', timestamp: '2026-06-01T12:00:00Z' },
    { id: '6', user_id: '1', action: 'WIP render received from Patrikas', related_creator_id: '4', related_deal_id: '4', related_campaign_id: null, related_payment_id: null, related_video_id: '3', old_value: 'Awaiting Draft', new_value: 'In Review', timestamp: '2026-06-26T09:00:00Z' },
  ],
  team_members: [
    { id: '1', name: 'Jeremy', email: 'jeremy@viggle.ai', role: 'Admin', created_at: '2026-01-01', updated_at: '2026-01-01' },
  ],
  supabase_url: '',
  supabase_key: '',
  current_user_id: '1',
};

function loadData() {
  try {
    const stored = localStorage.getItem(STORAGE_KEY);
    if (stored) {
      const parsed = JSON.parse(stored);
      const merged = { ...defaultData, ...parsed };
      // Patch audience_size + engagement_notes from defaultData for known creators
      // so updates to defaults are reflected without requiring a full reset
      if (merged.creators) {
        merged.creators = merged.creators.map(c => {
          const def = defaultData.creators.find(d => d.id === c.id);
          if (!def) return c;
          return {
            ...c,
            audience_size: c.audience_size === 0 && def.audience_size > 0 ? def.audience_size : c.audience_size,
            engagement_notes: (!c.engagement_notes || c.engagement_notes === '') && def.engagement_notes ? def.engagement_notes : c.engagement_notes,
          };
        });
      }
      // Merge Viggler contacts if not already present
      const existingIds = new Set(merged.creators.map(c => c.id));
      const trevor = merged.team_members.find(m => m.name && m.name.toLowerCase().includes('trevor'));
      const trevorId = trevor ? trevor.id : (merged.team_members[0] ? merged.team_members[0].id : '1');
      VIGGLER_CREATORS.forEach(c => {
        if (!existingIds.has(c.id)) {
          merged.creators.push({ ...c, owner_id: trevorId });
          existingIds.add(c.id);
        }
      });
      return merged;
    }
  } catch(e) {}
  // First load — include Vigglers in default data
  const base = { ...defaultData };
  const trevorId = base.team_members[0] ? base.team_members[0].id : '1';
  base.creators = [...base.creators, ...VIGGLER_CREATORS.map(c => ({ ...c, owner_id: trevorId }))];
  return base;
}

function saveData(data) {
  try { localStorage.setItem(STORAGE_KEY, JSON.stringify(data)); } catch(e) {}
}

function resetData() {
  localStorage.removeItem(STORAGE_KEY);
  return { ...defaultData };
}

window.CRM = { loadData, saveData, resetData, defaultData };
